Update

diff --git a/bin/git-credential-pass b/bin/git-credential-pass
--- a/bin/git-credential-pass
+++ b/bin/git-credential-pass
@@ -14,6 +14,7 @@ EOF
 }
 
 base=$HOME/.password-store/git
+gpgid=$HOME/.password-store/.gpg-id
 mkdir -p "$base"
 declare -A arr
 
@@ -44,10 +45,10 @@ get() {
 
 store () {
     file=$base/${arr[host]}.gpg
-    if [ -f ~/pass/.gpg-id ]; then
-        mail=$(cat ~/pass/.gpg-id)
+    if [ -f $gpgid ]; then
+        mail=$(cat $gpgid)
     else
-        echo "~/pass/.gpg-id not found. Please write email address to it." >&2
+        echo "$gpgid not found. Please write email address to it." >&2
         exit 1
     fi
 
@@ -71,12 +72,13 @@ erase () {
     # do not anything
 }
 
-args=$(getopt -u -o d:h --long help -- $*)
+args=$(getopt -u -o d:g:h --long help -- $*)
 set -- $args
 while [ $# -gt 0 ]; do 
     case $1 in 
     --) shift; break ;;
     -d) shift; base=$1 ;;
+    -g) shift; gpgid=$1 ;;
     -h|--help) help ;;
     esac
     shift
