Update

diff --git a/bin/git-credential-pass b/bin/git-credential-pass
--- a/bin/git-credential-pass
+++ b/bin/git-credential-pass
@@ -47,7 +47,7 @@ store () {
     if [ -f ~/pass/.gpg-id ]; then
         mail=$(cat ~/pass/.gpg-id)
     else
-        echo "require ~/pass/.gpg-id" >&2
+        echo "~/pass/.gpg-id not found. Please write email address to it." >&2
         exit 1
     fi
 
@@ -63,7 +63,6 @@ password=${arr[password]}"
         exit 1
     fi
     #echo "writing new password" >&2
-    mail=$(gpg2 --list-secret-keys|grep \< --color=no | sed -e 's/^.* <//' -e 's/>$//'|head -n 1)
     echo -en "$data" | gpg2 --yes -e -r "$mail" -o "$file"
 }
 
