Update

diff --git a/bin/git-credential-pass b/bin/git-credential-pass
--- a/bin/git-credential-pass
+++ b/bin/git-credential-pass
@@ -35,7 +35,7 @@ req () {
 get() {
     file=$base/${arr[host]}.gpg
     if [ -e "$file" ]; then
-        gpg -d "$file" | tee /tmp/test
+        gpg -d "$file"
     else
         # not found, do not anything
         exit 1
@@ -54,13 +54,14 @@ store () {
 }
 
 erase () {
-    file=$base/${arr[host]}.gpg
-    if [ -e "$file" ]; then
-        rm "$file"
-    else
-        echo "not found">&2
-        exit 1
-    fi
+    # do not anything
+    #file=$base/${arr[host]}.gpg
+    #if [ -e "$file" ]; then
+    #    rm "$file"
+    #else
+    #    echo "not found">&2
+    #    exit 1
+    #fi
 }
 
 args=$(getopt -u -o d:h --long help -- $*)
