Update

diff --git a/bin/repo b/bin/repo
--- a/bin/repo
+++ b/bin/repo
@@ -54,6 +54,18 @@ _update_repo()
         pushd "$repobase" >/dev/null
         _check_remote  "$name" "$remote_name" "$remote_url"
         branch_name=$(git branch | grep '*.*' | sed -e 's/\*\ //')
+        # check whether local branch exists this remote branch
+        if ! git branch -va | grep remotes/$remote_name/$branch_name" " >/dev/null ; then
+            # local branch does not exists this remote branch
+            # maybe upstream
+            ret=$(git fetch $remote_name 2>$DFTMP/git-fetch-stderr-$name-$remote_name &&:)
+            if [ $? -eq 0 ]; then
+                return 3
+            else
+                cat $DFTMP/git-fetch-stderr-$name-$remote_name
+                return 8
+            fi
+        fi
         ret=$(git -c color.status=always pull $remote_name $branch_name 2>$DFTMP/git-pull-stderr-$name-$remote_name &&:)
         if [ $? -eq 0 ]; then
             echo "$ret" | grep '^Already up[- ]to[- ]date.$' >/dev/null 2>&1 &&:
@@ -144,10 +156,12 @@ update_repo2()
             5) # conflict, abort merging
                 remote_status[$remote_name]="\e[31mconflict\e[m" ;;
             6) # branch not found
-                remote_status[$remote_name]="\e[35mnot find\e[m" ;;
+                remote_status[$remote_name]="\e[35mnot found\e[m" ;;
             7) # authentication failed
                 remote_status[$remote_name]="\e31mauth failure\e[m"
                 exit 1 ;;
+            8) # fetch failed
+                remote_status[$remote_name]="\e31mfetch failure\e[m" ;;
         esac
     done
 
